[location]
path = "../data"
overwrite = "true"

[data]
rec_filename = "kiva_recs.csv"
feature_filename = "kiva_item.csv"

[output]
filename = "history_file_product_lottery_rankedpairs_kiva.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "kiva_compat_dynamic.csv"


[feature]

[feature.one]
name = "COUNTRY_low_pfr"
protected_feature = "COUNTRY_low_pfr"
protected_values = [1]

[feature.two]
name = "loan_buck_5"
protected_feature = "loan_buck_5"
protected_values = [1]

[agent]

[agent.one]
name = "COUNTRY_low_pfr"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.one.metric]
feature = "COUNTRY_low_pfr"
proportion = 0.07

[agent.one.preference]
delta = 0.3
feature = "COUNTRY_low_pfr"

[agent.two]
name = "loan_buck_5"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.two.metric]
feature = "loan_buck_5"
proportion = 0.1

[agent.two.preference]
delta = 0.6
feature = "loan_buck_5"

[allocation]
allocation_class = "product_lottery"

[choice]
algorithm = "whalrus_scoring"
[choice.properties]
whalrus_rule = "RuleCopeland"
tie_breaker = "Random"
ignore_weights = false
recommender_weight = 0.8

[post]
postprocess_class = "ndcg"

[post.properties]
filename = "Copeland_prod_output_kiva.csv"
threshold = "none"
binary = "false"
