[location]
path = "../../data"
overwrite = "true"

[data]
rec_filename = "recs.csv"
feature_filename = "item.csv"

[output]
filename = "history_file_fairness_lottery_rankedpairslm.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat_least_to_most.csv"

[feature]

[feature.one]
name = "COUNTRY_low_pfr"
protected_feature = "COUNTRY_low_pfr"
protected_values = [1]

[feature.two]
name = "loan_buck_5"
protected_feature = "loan_buck_5"
protected_values = [1]

[agent]

[agent.one]
name = "COUNTRY_low_pfr"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.one.metric]
feature = "COUNTRY_low_pfr"
proportion = 0.2

[agent.one.preference]
delta = 0.1
feature = "COUNTRY_low_pfr"

[agent.two]
name = "loan_buck_5"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.two.metric]
feature = "loan_buck_5"
proportion = 0.3

[agent.two.preference]
delta = 0.1
feature = "loan_buck_5"

[allocation]
allocation_class = "least_fair"

[choice]
algorithm = "whalrus_scoring"
[choice.properties]
whalrus_rule = "RuleRankedPairs"
tie_breaker = "Ascending"
ignore_weights = false
recommender_weight = 0.8