[location]
path = "."
overwrite = "true"

[data]
rec_filename = "recs.csv"
feature_filename = "item.csv"

[output]
filename = "history_file_weighted_product.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 10

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "users.csv"

[feature]

[feature.one]
name = "One"
protected_feature = "1"
protected_values = [1]

[feature.two]
name = "Two"
protected_feature = "2"
protected_values = [1]

[agent]

[agent.one]
name = "Feature 1 Agent"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
choice_scorer_class = "fixed_value"

[agent.one.metric]
feature = "One"
proportion = 0.75

[agent.one.scorer]
protected_score_value = 0.5
protected_feature = "One"

[agent.two]
name = "Feature 2 Agent"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
choice_scorer_class = "fixed_value"

[agent.two.metric]
feature = "Two"
proportion = 0.5

[agent.two.scorer]
protected_score_value = 0.5
protected_feature = "Two"

[allocation]
allocation_class = "weighted_product_allocation_lottery"
no_agent_probability = 0.1

[choice]
choice_class = "weighted_rescore"

[choice.properties]
recommender_weight = 1.0
