[location]
path = "data"
overwrite = "true"

[data]
rec_filename = "recs_s1.csv"
feature_filename = "items_s1.csv"

[output]
filename = "history_file_basline.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat_s1.csv"

[feature]

[feature.one]
name = "0"
protected_feature = "0"
protected_values = [1]

[feature.two]
name = "1"
protected_feature = "1"
protected_values = [1]
[feature.three]
name = "2"
protected_feature = "2"
[feature.four]
name = "3"
protected_feature = "3"
[feature.five]
name = "4"
protected_feature = "4"
[feature.six]
name = "5"
protected_feature = "5"
[feature.seven]
name = "6"
protected_feature = "6"
[feature.eight]
name = "7"
protected_feature = "7"
[feature.nine]
name = "8"
protected_feature = "8"
[feature.ten]
name = "9"
protected_feature = "9"
[agent]

[agent.one]
name = "0"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.one.metric]
feature = "0"
proportion = 0.2

[agent.one.preference]
delta = 0.1
feature = "0"

[agent.two]
name = "1"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.two.metric]
feature = "1"
proportion = 0.4

[agent.two.preference]
delta = 0.1
feature = "1"

[allocation]
allocation_class = "weighted_product_allocation"

[allocation.properties]
compatibility_exponent = 2
fairness_exponent = 1

[choice]
choice_class = "OFAIR"

[choice.properties]
recommender_weight = 0.51
non_sensitive_discount = 100
epsilon = 0.00000000000000022
alpha = 1.0

[post]
postprocess_class = "null"



