[location]
path = "../data"
overwrite = "true"

[data]
rec_filename = "recs_s1.csv"
feature_filename = "items_s1.csv"

[output]
filename = "history_file_product_alloc_rescore_s1.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat_s1.csv"

[feature]

[feature.one]
name = "0"
protected_feature = "0"
protected_values = [1]

[feature.two]
name = "1"
protected_feature = "1"
protected_values = [1]

[agent]

[agent.one]
name = "0"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.one.metric]
feature = "0"
proportion = 0.2

[agent.one.preference]
delta = 0.1
feature = "0"

[agent.two]
name = "1"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.two.metric]
feature = "1"
proportion = 0.5

[agent.two.preference]
delta = 0.1
feature = "1"

[allocation]
allocation_class = "weighted_product_allocation"

[allocation.properties]
compatibility_exponent = 1
fairness_exponent = 1

[choice]
algorithm = "weighted_scoring"
[choice.properties]

recommender_weight = 0.8

[post]
postprocess_class = "ndcg"

[post.properties]
filename = "Rescore_prod_outputs1.csv"
threshold = "none"
binary = "false"
