[location]
path = "../../data"
overwrite = "true"

[data]
rec_filename = "recs.csv"
feature_filename = "item.csv"

[output]
filename = "history_file_most_compatible_borda.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat.csv"

[feature]

[feature.one]
name = "1"
protected_feature = "1"
protected_values = [1]

[feature.two]
name = "2"
protected_feature = "2"
protected_values = [1]

[agent]

[agent.one]
name = "1"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.one.metric]
feature = "1"
proportion = 0.07

[agent.one.preference]
delta = 0.1
feature = "1"

[agent.two]
name = "2"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.two.metric]
feature = "2"
proportion = 0.1

[agent.two.preference]
delta = 0.1
feature = "2"

[allocation]
allocation_class = "most_compatible"

[choice]
choice_class = "whalrus_scoring"
[choice.properties]
whalrus_rule = "RuleBorda"
tie_breaker = "None"
ignore_weights = false
recommender_weight = 0.8
