[location]
path = "../../data"
overwrite = "true"

[data]
rec_filename = "recs.csv"
feature_filename = "loan_feature_df_hc_10core.csv"

[output]
filename = "history_file_fairness_lottery.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat.csv"

[feature]

[feature.one]
name = "loan_buck_5"
protected_feature = "loan_buck_5"
protected_values = [1]

[feature.two]
name = "COUNTRY_low_pfr"
protected_feature = "COUNTRY_low_pfr"
protected_values = [1]

[agent]

[agent.one]
name = "loan_buck_5"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.one.metric]
feature = "loan_buck_5"
proportion = 0.9

[agent.one.preference]
delta = 0.5
feature = "1"

[agent.two]
name = "COUNTRY_low_pfr"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "binary_preference"

[agent.two.metric]
feature = "2"
proportion = 0.9

[agent.two.preference]
delta = 0.5
feature = "2"

[allocation]
allocation_class = "fairness_lottery"

[choice]
algorithm = "whalrus_scoring"
[choice.properties]
whalrus_rule = "RuleBorda"
tie_breaker = "None"
ignore_weights = false
recommender_weight = 0.8
